/*
 * managerframe.java
 *
 * Created on __DATE__, __TIME__
 */

package frame;

import java.io.InputStream;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;

import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;

import entity.ManagerAssign;
import entity.ManagerRevoke;
import entity.Users;

import test.test;

/**
 * 
 * @author __USER__
 */
public class Managerframe extends javax.swing.JFrame {

	/**
	 * Creates new form managerframe
	 * 
	 * @param managerpsddatabase
	 * @param username
	 */
	static String manageername;
	static String managerrole;
	boolean isassignrole = true;
	boolean isrevokerole = true;

	public Managerframe(String username, String managerrole) {
		this.manageername = username;
		this.managerrole = managerrole;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldpanel1username = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jPasswordFieldpanel1psd = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jComboBoxpanel1selectrole = new javax.swing.JComboBox();
		jButtonpanel1createuser = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabelmanagername = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabelmanagerrole = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jLabelmanagername1 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabelmanagerrole1 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextFieldpanel2username = new javax.swing.JTextField();
		jButtonpannel2select = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jLabelpanel2userrole = new javax.swing.JLabel();
		jLabelpanel2username = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabepanel2userrole = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jComboBoxpanel2role = new javax.swing.JComboBox();
		jButtonpanel2addrole = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabelpanel3managername = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabelpanel3managerrole = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jTextFieldpanel3username = new javax.swing.JTextField();
		jButtonpannel3select = new javax.swing.JButton();
		jLabel15 = new javax.swing.JLabel();
		jLabelpanel3username = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabepanel3userrole = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jComboBoxpanel3role = new javax.swing.JComboBox();
		jButtonpanel3revokerole = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u7528\u6237\u540d");

		jLabel2.setText("\u5bc6   \u7801");

		jLabel3.setText("\u5206\u914d\u89d2\u8272");

		jComboBoxpanel1selectrole
				.setModel(new javax.swing.DefaultComboBoxModel(
						new String[] { "基础员工" }));

		jButtonpanel1createuser.setText("\u786e\u8ba4\u521b\u5efa");
		jButtonpanel1createuser
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonpanel1createuserActionPerformed(evt);
					}
				});

		jLabel4.setText("\u5f53\u524d\u7ba1\u7406\u5458");

		jLabelmanagername.setForeground(new java.awt.Color(255, 51, 51));
		jLabelmanagername.setText(manageername);

		jLabel5.setText("\u7ba1\u7406\u5458\u89d2\u8272");

		jLabelmanagerrole.setForeground(new java.awt.Color(255, 51, 51));
		jLabelmanagerrole.setText(managerrole);

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(43, 43, 43)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel4)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.UNRELATED)
												.add(jLabelmanagername,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														52,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(45, 45, 45)
												.add(jLabel5)
												.add(18, 18, 18)
												.add(jLabelmanagerrole,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														69,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jLabel1)
										.add(jLabel2)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel3)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(49, 49, 49)
																.add(jButtonpanel1createuser))
														.add(jPanel1Layout
																.createSequentialGroup()
																.add(18, 18, 18)
																.add(jPanel1Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING,
																				false)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING,
																				jPasswordFieldpanel1psd)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING,
																				jComboBoxpanel1selectrole,
																				0,
																				125,
																				Short.MAX_VALUE)
																		.add(org.jdesktop.layout.GroupLayout.TRAILING,
																				jTextFieldpanel1username))))))
								.addContainerGap(36, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jLabel4)
												.add(jLabelmanagername,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														17,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel1Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jLabel5)
												.add(jLabelmanagerrole,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														17,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.add(39, 39, 39)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jLabel1)
										.add(jTextFieldpanel1username,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED,
										28, Short.MAX_VALUE)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel2)
										.add(jPasswordFieldpanel1psd,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(18, 18, 18)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel3)
										.add(jComboBoxpanel1selectrole,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(27, 27, 27).add(jButtonpanel1createuser)
								.add(34, 34, 34)));

		jTabbedPane1.addTab("\u521b\u5efa\u7528\u6237", jPanel1);

		jLabel6.setText("\u5f53\u524d\u7ba1\u7406\u5458");

		jLabelmanagername1.setForeground(new java.awt.Color(255, 51, 51));
		jLabelmanagername1.setText(manageername);

		jLabel7.setText("\u7ba1\u7406\u5458\u89d2\u8272");

		jLabelmanagerrole1.setForeground(new java.awt.Color(255, 51, 51));
		jLabelmanagerrole1.setText(managerrole);

		jLabel8.setText("\u67e5\u627e\u7528\u6237");

		jButtonpannel2select.setText("\u67e5\u627e");
		jButtonpannel2select
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonpannel2selectActionPerformed(evt);
					}
				});

		jLabel9.setText("\u7528\u6237\u540d");

		jLabel10.setText("\u7528\u6237\u89d2\u8272");

		jLabel12.setText("\u53ef\u6388\u4e88\u89d2\u8272");

		jButtonpanel2addrole.setText("\u786e\u5b9a\u6388\u4e88");
		jButtonpanel2addrole
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonpanel2addroleActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel2Layout
								.createSequentialGroup()
								.add(42, 42, 42)
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel2Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.TRAILING)
												.add(jLabel6)
												.add(jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel12)
														.add(jLabel10)
														.add(jLabel9)))
										.add(jLabel8))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel2Layout
												.createSequentialGroup()
												.add(jPanel2Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel2Layout
																.createSequentialGroup()
																.add(jLabelmanagername1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		52,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(60, 60, 60)
																.add(jLabel7)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jLabelmanagerrole1,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		69,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(jPanel2Layout
																.createSequentialGroup()
																.add(jTextFieldpanel2username,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		114,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(18, 18, 18)
																.add(jButtonpannel2select))
														.add(jPanel2Layout
																.createSequentialGroup()
																.add(jLabelpanel2username,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		75,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jLabelpanel2userrole,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		126,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(jLabepanel2userrole,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																274,
																Short.MAX_VALUE))
												.addContainerGap())
										.add(org.jdesktop.layout.GroupLayout.TRAILING,
												jPanel2Layout
														.createSequentialGroup()
														.add(jComboBoxpanel2role,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																89,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED,
																45,
																Short.MAX_VALUE)
														.add(jButtonpanel2addrole)
														.add(71, 71, 71)))));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel2Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jLabelmanagerrole1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												17,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel7)
										.add(jLabelmanagername1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												17,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel6))
								.add(18, 18, 18)
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jTextFieldpanel2username,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jButtonpannel2select).add(jLabel8))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jPanel2Layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING,
														false)
												.add(jLabelpanel2username,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.add(jLabelpanel2userrole,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														17, Short.MAX_VALUE))
										.add(jLabel9,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel10)
										.add(jLabepanel2userrole,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												17,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(18, 18, 18)
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel12)
										.add(jButtonpanel2addrole)
										.add(jComboBoxpanel2role,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(102, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u589e\u52a0\u89d2\u8272", jPanel2);

		jLabel11.setText("\u5f53\u524d\u7ba1\u7406\u5458");

		jLabelpanel3managername.setForeground(new java.awt.Color(255, 51, 51));
		jLabelpanel3managername.setText(manageername);

		jLabel13.setText("\u7ba1\u7406\u5458\u89d2\u8272");

		jLabelpanel3managerrole.setForeground(new java.awt.Color(255, 51, 51));
		jLabelpanel3managerrole.setText(managerrole);

		jLabel14.setText("\u67e5\u627e\u7528\u6237");

		jButtonpannel3select.setText("\u67e5\u627e");
		jButtonpannel3select
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonpannel3selectActionPerformed(evt);
					}
				});

		jLabel15.setText("\u7528\u6237\u540d");

		jLabel16.setText("\u7528\u6237\u89d2\u8272");

		jLabel17.setText("\u53ef\u5220\u9664\u89d2\u8272");

		jButtonpanel3revokerole.setText("\u786e\u5b9a\u5220\u9664");
		jButtonpanel3revokerole
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonpanel3revokeroleActionPerformed(evt);
					}
				});

		org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel3Layout
								.createSequentialGroup()
								.add(46, 46, 46)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel3Layout
												.createSequentialGroup()
												.add(jPanel3Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jPanel3Layout
																.createSequentialGroup()
																.add(jLabel16)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.UNRELATED)
																.add(jLabepanel3userrole,
																		org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																		269,
																		Short.MAX_VALUE)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED))
														.add(jPanel3Layout
																.createSequentialGroup()
																.add(jLabel11)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.UNRELATED)
																.add(jLabelpanel3managername,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		52,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(46, 46, 46)
																.add(jLabel13)
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jLabelpanel3managerrole,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		69,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
														.add(jPanel3Layout
																.createSequentialGroup()
																.add(jPanel3Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(jLabel14)
																		.add(jLabel15))
																.addPreferredGap(
																		org.jdesktop.layout.LayoutStyle.RELATED)
																.add(jPanel3Layout
																		.createParallelGroup(
																				org.jdesktop.layout.GroupLayout.LEADING)
																		.add(jPanel3Layout
																				.createSequentialGroup()
																				.add(jTextFieldpanel3username,
																						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																						114,
																						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						org.jdesktop.layout.LayoutStyle.UNRELATED)
																				.add(jButtonpannel3select))
																		.add(jLabelpanel3username,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				75,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
												.addContainerGap(
														20,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel3Layout
												.createSequentialGroup()
												.add(jLabel17)
												.add(18, 18, 18)
												.add(jComboBoxpanel3role,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														117,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED,
														28, Short.MAX_VALUE)
												.add(jButtonpanel3revokerole)
												.add(45, 45, 45)))));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel3Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel11)
										.add(jLabelpanel3managername,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												17,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel13)
										.add(jLabelpanel3managerrole,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												17,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(27, 27, 27)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel14)
										.add(jTextFieldpanel3username,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jButtonpannel3select))
								.add(18, 18, 18)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jLabelpanel3username,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												17, Short.MAX_VALUE)
										.add(jLabel15,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.TRAILING)
										.add(jLabel16)
										.add(jLabepanel3userrole,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												17,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(18, 18, 18)
								.add(jPanel3Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel17)
										.add(jButtonpanel3revokerole)
										.add(jComboBoxpanel3role,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(91, 91, 91)));

		jTabbedPane1.addTab("\u56de\u6536\u89d2\u8272", jPanel3);

		org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 395,
				Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(0, 269,
				Short.MAX_VALUE));

		jTabbedPane1.addTab("tab4", jPanel4);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jTabbedPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jTabbedPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	//回收角色按钮

	private void jButtonpanel3revokeroleActionPerformed(
			java.awt.event.ActionEvent evt) {
		//判断是否有删除的角色
		if (isrevokerole == false) {
			JOptionPane.showMessageDialog(this, "当前管理员相对于该用户没有可以回收的角色！",
					"回收角色信息", JOptionPane.WARNING_MESSAGE);
		} else {
			//获取当前用户角色
			String revokeroleString = jComboBoxpanel3role.getSelectedItem()
					.toString();
			SqlSession session = null;
			SqlSessionFactory sessionFactory = null;
			InputStream is = test.class.getClassLoader().getResourceAsStream(
					"data/conf.xml");
			sessionFactory = new SqlSessionFactoryBuilder().build(is);
			session = sessionFactory.openSession();
			SqlSession session2 = sessionFactory.openSession();
			String inputusername = jTextFieldpanel3username.getText();
			String statement = "data.Mapper.selectusersbyname";
			Users nowusers = session.selectOne(statement, inputusername);
			String nowroleString = nowusers.getRole();
			nowroleString = nowroleString.replace(revokeroleString, "");
			nowusers.setRole(nowroleString);
			statement = "data.Mapper.updateuserrole";
			session.update(statement, nowusers);
			session.commit();
			session.close();
			JOptionPane.showMessageDialog(this, "删除角色成功！", "删除信息",
					JOptionPane.INFORMATION_MESSAGE);
		}
		jButtonpannel3selectActionPerformed(evt);
	}

	//查询回收角色
	void jButtonpannel3selectActionPerformed(java.awt.event.ActionEvent evt) {
		jComboBoxpanel3role.removeAllItems();
		SqlSession session = null;
		SqlSessionFactory sessionFactory = null;
		InputStream is = test.class.getClassLoader().getResourceAsStream(
				"data/conf.xml");
		sessionFactory = new SqlSessionFactoryBuilder().build(is);
		session = sessionFactory.openSession();
		SqlSession session2 = sessionFactory.openSession();
		String inputusername = jTextFieldpanel3username.getText();

		String statement = "data.Mapper.selectusersbyname";
		Users usertest2 = session.selectOne(statement, inputusername);
		session.commit();
		session.close();
		// 判断是否能找到该用户
		if (usertest2 == null) {
			JOptionPane.showMessageDialog(this, "未找到该用户！", "查找信息",
					JOptionPane.WARNING_MESSAGE);
		} else {
			jLabelpanel3username.setText(usertest2.getUsername());
			jLabepanel3userrole.setText(usertest2.getRole());
			List<String> userrolelist = Arrays.asList(usertest2.getRole()
					.split(" "));
			//判定当前管理员可删除回收的角色，并显示到combox中去
			statement = "data.Mapper.selectrevoke";
			ManagerRevoke MR = new ManagerRevoke();
			MR.setManagerrole("公司主管");
			ManagerRevoke nowMR = session2.selectOne(statement, MR);
			String revokeroleString = nowMR.getRevokerole();
			String canrevoke[] = new String[50];
			System.out.println(revokeroleString);
			int k = 0;
			for (int i = 0; i < userrolelist.size(); i++) {
				//判定当前用户的角色与管理员可回收角色的交集
				boolean index = revokeroleString.contains(userrolelist.get(i));
				if (index == true) {
					canrevoke[k] = userrolelist.get(i);
					k++;
				}
			}
			if (k == 0) {
				isrevokerole = false;
			} else {
				for (int i = 0; i < k; i++) {
					//jComboBoxpanel2role.setModel(null);
					jComboBoxpanel3role.addItem(canrevoke[i]);
				}
				System.out.println(k);
				session2.commit();
				session2.close();
			}
		}
	}

	//授予权限按钮

	private void jButtonpanel2addroleActionPerformed(
			java.awt.event.ActionEvent evt) {
		if (isassignrole == false) {
			JOptionPane.showMessageDialog(this, "可授予角色为空，增加失败！", "增加信息",
					JOptionPane.WARNING_MESSAGE);
		} else {
			SqlSession session = null;
			SqlSessionFactory sessionFactory = null;
			InputStream is = test.class.getClassLoader().getResourceAsStream(
					"data/conf.xml");
			sessionFactory = new SqlSessionFactoryBuilder().build(is);
			session = sessionFactory.openSession();
			String addroleString = jComboBoxpanel2role.getSelectedItem()
					.toString();
			//先找到该用户
			String statement = "data.Mapper.selectusersbyname";
			String inputusername = jTextFieldpanel2username.getText();
			Users nowuser = session.selectOne(statement, inputusername);
			String nowuserrole = nowuser.getRole();
			nowuserrole = nowuserrole + " " + addroleString;
			nowuser.setRole(nowuserrole);
			System.out.println(nowuserrole);
			statement = "data.Mapper.updateuserrole";
			session.update(statement, nowuser);
			session.commit();
			session.close();
			JOptionPane.showMessageDialog(this, "增加角色成功！", "增加信息",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void jButtonpannel2selectActionPerformed(
			java.awt.event.ActionEvent evt) {
		jComboBoxpanel2role.removeAllItems();
		SqlSession session = null;
		SqlSessionFactory sessionFactory = null;
		InputStream is = test.class.getClassLoader().getResourceAsStream(
				"data/conf.xml");
		sessionFactory = new SqlSessionFactoryBuilder().build(is);
		session = sessionFactory.openSession();
		SqlSession session2 = sessionFactory.openSession();
		String inputusername = jTextFieldpanel2username.getText();

		String statement = "data.Mapper.selectusersbyname";
		Users usertest2 = session.selectOne(statement, inputusername);
		session.commit();
		session.close();
		// 判断是否能找到该用户
		if (usertest2 == null) {
			JOptionPane.showMessageDialog(this, "未找到该用户！", "查找信息",
					JOptionPane.WARNING_MESSAGE);
		} else {
			jLabelpanel2username.setText(usertest2.getUsername());
			jLabepanel2userrole.setText(usertest2.getRole());
			//判断用户的role是否为产品1的还是产品2的
			int roletype012;
			if ((usertest2.getRole()).contains("1")) {
				roletype012=1;//1产品部门
			} else if ((usertest2.getRole()).contains("2")) {
				roletype012=2;//2产品部门
			}else {
				roletype012=0;
			}
			List<String> userrolelist = Arrays.asList(usertest2.getRole()
					.split(" "));
			ManagerAssign managerAssign = new ManagerAssign();
			managerAssign.setManagerrole(managerrole);
			String canassignrole[] = new String[50];
			// 遍历整个数组，查询可以赋予的角色
			int k = 0;
			for (int i = 0; i < userrolelist.size(); i++) {
				managerAssign.setUserrole(userrolelist.get(i));
				String statement2 = "data.Mapper.selectassign";
				ManagerAssign MA = session2
						.selectOne(statement2, managerAssign);
				//判断返回MA是否为空
				if (MA==null) {
					//为空则什么都不做
				} else {
					List<String> assignrolelist = Arrays.asList(MA.getAssignrole()
							.split(" "));
					for (int j = 0; j < assignrolelist.size(); j++) {
						if (MA != null) {
							//1.判断角色中是否包含可授予角色 2.判断可授予角色中是否已经有重复项 3.实现静态职责分析
							boolean index1 = userrolelist.contains(assignrolelist.get(j));
							int index2;
							int index3=1;//职责分离
							
							if (roletype012==1) {
								if ((assignrolelist.get(j)).contains("2")) {
									index3=0;
								} else {
									index3=1;
								}
							} else if (roletype012==2) {
								if ((assignrolelist.get(j)).contains("1")) {
									index3=0;
								} else {
									index3=1;
								}
							}
							//若初始可授予角色数组为空，则跳过这一环节
							if (k == 0) {
								index2 = -1;
							} else {
								System.out.println(canassignrole[i]);
								List<String> tempList = Arrays.asList(canassignrole);

								//利用list的包含方法，进行判断
								if(tempList.contains(assignrolelist.get(j)))
								{
									index2=1;
								}else {
									index2=-1;
								}
								/*Arrays.sort(canassignrole);
								index2 = Arrays.binarySearch(canassignrole,
										assignrolelist.get(j));*/

							}

							if (index2 == -1 && !index1 &&index3==1) {
								canassignrole[k] = assignrolelist.get(j);
								k++;
							}
						}
					}
				}
				

			}
			// 判断可赋予角色是否为空
			if (k == 0) {
				isassignrole = false;
			} else {
				for (int i = 0; i < k; i++) {
					//jComboBoxpanel2role.setModel(null);
					jComboBoxpanel2role.addItem(canassignrole[i]);
				}

			}
			System.out.println(k);
			session2.commit();
			session2.close();
		}
	}

	private void jButtonpanel1createuserActionPerformed(
			java.awt.event.ActionEvent evt) {
		SqlSession session = null;
		SqlSessionFactory sessionFactory = null;
		InputStream is = test.class.getClassLoader().getResourceAsStream(
				"data/conf.xml");
		sessionFactory = new SqlSessionFactoryBuilder().build(is);
		session = sessionFactory.openSession();
		String username = jTextFieldpanel1username.getText();
		String psd = jPasswordFieldpanel1psd.getText();
		String role = jComboBoxpanel1selectrole.getSelectedItem().toString();
		;
		String statement = "data.Mapper.selectusersbyname";
		Users usertest1 = session.selectOne(statement, username);
		// 判断是否已有该用户信息
		if (usertest1 == null) {
			Users user = new Users();
			user.setUsername(username);
			user.setUserpsd(psd);
			user.setRole(role);
			statement = "data.Mapper.insertuser";
			session.insert(statement, user);
			session.commit();
			session.close();
			JOptionPane.showMessageDialog(this, "创建成功！", "创建信息",
					JOptionPane.INFORMATION_MESSAGE);
		} else {
			JOptionPane.showMessageDialog(this, "创建失败，已有该用户信息！", "创建信息",
					JOptionPane.WARNING_MESSAGE);
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Managerframe(manageername, managerrole).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonpanel1createuser;
	private javax.swing.JButton jButtonpanel2addrole;
	private javax.swing.JButton jButtonpanel3revokerole;
	private javax.swing.JButton jButtonpannel2select;
	private javax.swing.JButton jButtonpannel3select;
	private javax.swing.JComboBox jComboBoxpanel1selectrole;
	private javax.swing.JComboBox jComboBoxpanel2role;
	private javax.swing.JComboBox jComboBoxpanel3role;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLabel jLabelmanagername;
	private javax.swing.JLabel jLabelmanagername1;
	private javax.swing.JLabel jLabelmanagerrole;
	private javax.swing.JLabel jLabelmanagerrole1;
	private javax.swing.JLabel jLabelpanel2username;
	private javax.swing.JLabel jLabelpanel2userrole;
	private javax.swing.JLabel jLabelpanel3managername;
	private javax.swing.JLabel jLabelpanel3managerrole;
	private javax.swing.JLabel jLabelpanel3username;
	private javax.swing.JLabel jLabepanel2userrole;
	private javax.swing.JLabel jLabepanel3userrole;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPasswordField jPasswordFieldpanel1psd;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextFieldpanel1username;
	private javax.swing.JTextField jTextFieldpanel2username;
	private javax.swing.JTextField jTextFieldpanel3username;
	// End of variables declaration//GEN-END:variables

}