/*
 * frame2.java
 *
 * Created on __DATE__, __TIME__
 */

package frame;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;

import entity.Users;

import test.test;

/**
 *
 * @author  __USER__
 */
public class Userframe extends javax.swing.JFrame {

	private File f;
	static String username;
	static String userrole;
	private static String perString="";
	private static boolean shouldcleartextarea = false;
	int HadView=0;
	/** Creates new form frame2 */
	public Userframe(String username, String userrole) {
		this.username = username;
		this.userrole = userrole;
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabelusername = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabeluserrole = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButtonselect = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextAreaword = new javax.swing.JTextArea();
		jButtonupdate = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("\u5f53\u524d\u7528\u6237\uff1a");

		jLabelusername.setText(username);

		jLabel3.setText("\u5f53\u524d\u89d2\u8272\uff1a");

		jLabeluserrole.setText(userrole);

		jLabel2.setText("\u9009\u62e9\u8d44\u6e90");

		jButtonselect.setText("\u9009\u62e9\u67e5\u770b");
		jButtonselect.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonselectActionPerformed(evt);
			}
		});

		jTextAreaword.setColumns(20);
		jTextAreaword.setRows(5);
		jScrollPane1.setViewportView(jTextAreaword);

		jButtonupdate.setText("\u4fdd\u5b58\u4fee\u6539");
		jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonupdateActionPerformed(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(87, 87, 87)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jLabel1)
														.add(jLabel3)
														.add(jLabel2))
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(jButtonselect)
														.add(jLabeluserrole)
														.add(jLabelusername)))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(183, 183, 183)
												.add(jButtonupdate))
										.add(jPanel1Layout
												.createSequentialGroup()
												.addContainerGap()
												.add(jScrollPane1,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														447, Short.MAX_VALUE)))
								.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel1).add(jLabelusername))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel3).add(jLabeluserrole))
								.add(18, 18, 18)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel2).add(jButtonselect))
								.add(18, 18, 18)
								.add(jScrollPane1,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										243, Short.MAX_VALUE)
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jButtonupdate).add(38, 38, 38)));

		jTabbedPane1.addTab("\u64cd\u4f5c\u754c\u9762", jPanel1);

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jTabbedPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(jTabbedPane1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 462,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {
		
		String filename = f.getName();
		filename = filename.substring(0, filename.length() - 4);
		String activeString = "修改" + filename;
		//判断用户权限中是否包括修改文件
		if (perString.indexOf(activeString) == -1) {
			JOptionPane.showMessageDialog(this, "当前用户权限不足，不能保存修改！", "修改受限",
					JOptionPane.WARNING_MESSAGE);
		} else {
			String text = jTextAreaword.getText();
			String[] lines = text.trim().split("\n");
			try {
				PrintWriter out = new PrintWriter(new FileOutputStream(f), true);
				for (String line : lines)
					out.println(line);
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}

	}

	private void jButtonselectActionPerformed(java.awt.event.ActionEvent evt) {
		if (shouldcleartextarea) {
			jTextAreaword.setText("");
		}
		JFileChooser fd = new JFileChooser();
		//fd.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); 
		fd.setCurrentDirectory(new File("D:/java/访问控制课设资料"));
		fd.showOpenDialog(null);
		f = fd.getSelectedFile();
		String filename = f.getName();
		filename = filename.substring(0, filename.length() - 4);//获取文件名
		if (HadView==1 && filename.contains("2")) {
			JOptionPane.showMessageDialog(this, "当前已经查询过1产品信息，不能在本次会话中查看2产品信息！", "查看受限",
					JOptionPane.WARNING_MESSAGE);
		} else if (HadView==2 && filename.contains("1")) {
			JOptionPane.showMessageDialog(this, "当前已经查询过2产品信息，不能在本次会话中查看1产品信息！", "查看受限",
					JOptionPane.WARNING_MESSAGE);
		}else {
			SqlSession session = null;
			SqlSessionFactory sessionFactory = null;
			InputStream is = test.class.getClassLoader().getResourceAsStream(
					"data/conf.xml");
			sessionFactory = new SqlSessionFactoryBuilder().build(is);
			session = sessionFactory.openSession();
			String statement = "data.Mapper.selectuserperbyrole";
			List<String> userrolelist =Arrays.asList(userrole.split(" "));
			//循环遍历查询权限
			//String perString = "";
			for (int i = 0; i < userrolelist.size(); i++) {
				String oneper = session.selectOne(statement, userrolelist.get(i));
				perString=perString+oneper+" ";
			}
			perString = perString.substring(0, perString.length()-1);
			System.out.println(perString);
			//List<String> userperlist =Arrays.asList(perString.split(" "));//获得用户对应权限
			String activeString = "查看" + filename;
			boolean iscontain=false;
			if (perString.indexOf(activeString)==-1) {
				//如果权限中不包括查看该文件
				JOptionPane.showMessageDialog(this, "当前用户权限不足，不能查看该文件！", "查看受限",
						JOptionPane.WARNING_MESSAGE);
			} else {
				//System.out.println(roleString);
				try {
					BufferedReader reader = new BufferedReader(
							new InputStreamReader(new FileInputStream(f), "gbk"));
					String line = null;
					while ((line = reader.readLine()) != null) {
						jTextAreaword.append(line + "\n");
					}
				} catch (Exception e) {
					// TODO: handle exception
				}
			}
			session.close();
			shouldcleartextarea = true;
			if (filename.contains("1")) {
				HadView=1;
			} else if (filename.contains("2")) {
				HadView=2;
			}
		}
		
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Userframe(username, userrole).setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButtonselect;
	private javax.swing.JButton jButtonupdate;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabelusername;
	private javax.swing.JLabel jLabeluserrole;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextArea jTextAreaword;
	// End of variables declaration//GEN-END:variables

}